name: RKNYMAN
favicon: null
layout_spectrum: 0.5657227302435786
typography_spectrum: 0.17070644022896886
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8779610225465149
  lightness: 0.6694610307458788
  saturation: 0.40434866887517273
  rhythmicContrast: 0.4821879710070789
purpose: []
